### PR TITLE
Pull Req

### PR DESCRIPTION
**Pull request by MeltricCode**

### CODE REVIEW

**Comment by MeltricCode** [comment]
Commited By Phone(cause i dont have access to pc right now:))

**Review by mohammadKarimi — COMMENTED** [review]
Where is your INotificationService? did you add it to code base?

**Comment by MeltricCode** [comment]
No i just Added the Name, i will impliment that today(Ithough its only
guess name :))

**Comment by MeltricCode** [comment]
> Where is your INotificationService? did you add it to code base?

Its Compelete Right Now

**Review by mohammadKarimi — COMMENTED** [review]
Well done

**Pull request closed without merging**
